--- #YAML:1.0
name:                Net-Amazon-S3
version:             0.44
abstract:            ~
license:             perl
author:              
    - Leon Brocard <acme@astray.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Class::Accessor::Fast:         0
    DateTime::Format::Strptime:    0
    Digest::HMAC_SHA1:             0
    Digest::MD5::File:             0
    HTTP::Date:                    0
    LWP::UserAgent::Determined:    0
    MIME::Base64:                  0
    Test::More:                    0.01
    URI::Escape:                   0
    XML::LibXML:                   0
    XML::LibXML::XPathContext:     0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
