--- #YAML:1.0
name:               Net-Amazon-S3
version:            0.54
abstract:           Use the Amazon S3 - Simple Storage Service
author:
    - Pedro Figueiredo <me@pedrofigueiredo.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::MOP:           0.88
    Data::Stream::Bulk:   0.06
    DateTime::Format::HTTP:  0
    DateTime::Format::ISO8601:  0
    Digest::HMAC_SHA1:    0
    Digest::MD5:          0
    Digest::MD5::File:    0
    File::stat:           0
    HTTP::Date:           0
    HTTP::Status:         0
    IO::File:             1.14
    LWP::UserAgent::Determined:  0
    MIME::Base64:         0
    Moose:                0.85
    MooseX::StrictConstructor:  0.08
    MooseX::Types::DateTimeX:  0
    Regexp::Common:       0
    Test::More:           0.01
    URI::Escape:          0
    XML::LibXML:          0
    XML::LibXML::XPathContext:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
